//
//  LanguageManager.ts
//  Rentify
//
//  Created by Tin Pham on 27/7/26.
//

import { useState, useEffect } from 'react';
import * as Localization from 'expo-localization';

export type Language = 'en' | 'vi';

export const translations: Record<string, Record<Language, string>> = {
  subtitle: { en: "Rental management at your fingertips", vi: "Quản lý phòng trọ trong tầm tay" },
  landlord: { en: "Landlord", vi: "Chủ nhà" },
  tenant: { en: "Tenant", vi: "Người thuê" },
  phone_number: { en: "PHONE NUMBER", vi: "SỐ ĐIỆN THOẠI" },
  password: { en: "PASSWORD", vi: "MẬT KHẨU" },
  log_in: { en: "Log In", vi: "Đăng nhập" },
  quick_login: { en: "QUICK LOGIN", vi: "ĐĂNG NHẬP NHANH" },
  log_in_as: { en: "Log in as", vi: "Đăng nhập làm" },
  
  // Onboarding Keys
  ob_title_1: { en: "Smart Operations", vi: "Vận hành thông minh" },
  ob_desc_1: { en: "Automate rent invoices, calculate electric/water meters, and trace active lease details in one clean dashboard.", vi: "Tự động hóa hóa đơn, tính số điện nước và theo dõi thông tin hợp đồng dễ dàng." },
  ob_title_2: { en: "Community Board", vi: "Bảng tin cư dân" },
  ob_desc_2: { en: "Broadcast building rules, maintenance intervals, and updates inside a verified local resident bulletin.", vi: "Xem quy định phòng trọ, lịch bảo trì và trao đổi tin tức nội bộ an toàn." },
  ob_title_3: { en: "Emergency Broadcast", vi: "Thông báo khẩn cấp" },
  ob_desc_3: { en: "Notify residents instantly about maintenance issues, or trigger immediate building fire alerts.", vi: "Nhận thông báo khẩn từ chủ nhà hoặc tự kích hoạt báo động cháy khi phát hiện sự cố." },
  ob_skip: { en: "Skip", vi: "Bỏ qua" },
  ob_next: { en: "Next", vi: "Tiếp tục" },
  ob_start: { en: "Get Started", vi: "Bắt đầu" },
  
  // Errors
  err_phone_empty: { en: "Phone number cannot be empty.", vi: "Số điện thoại không được để trống." },
  err_password_short: { en: "Password must be at least 6 characters long.", vi: "Mật khẩu phải có ít nhất 6 ký tự." },
  err_login_failed: { en: "An error occurred during login.", vi: "Đã xảy ra lỗi khi đăng nhập." },
  err_phone_digits_vi: { en: "Phone number must be exactly 9 digits for +84.", vi: "Số điện thoại phải có đúng 9 chữ số cho +84." },
  err_phone_digits_us: { en: "Phone number must be exactly 10 digits for +1.", vi: "Số điện thoại phải có đúng 10 chữ số cho +1." },
  err_phone_digits_sg: { en: "Phone number must be exactly 8 digits for +65.", vi: "Số điện thoại phải có đúng 8 chữ số cho +65." },

  // Notices
  bulletin_board: { en: "Bulletin Board", vi: "Bảng tin cư dân" },
  announcements: { en: "Announcements", vi: "Thông báo" },
  bulletin_empty: { en: "Bulletin Empty", vi: "Bảng tin trống" },
  bulletin_empty_desc: { en: "There are no community notifications or emergency alerts at the moment.", vi: "Hiện tại không có thông báo cộng đồng hoặc cảnh báo khẩn cấp nào." },
  no_announcements: { en: "No Announcements", vi: "Chưa Có Thông Báo" },
  no_announcements_desc: { en: "Send an announcement or alert to all occupants of this property.", vi: "Gửi thông báo hoặc cảnh báo cho tất cả cư dân trong tòa nhà." },
  sender_prefix: { en: "From: ", vi: "Từ: " },
  report_fire: { en: "Report Fire", vi: "Báo Cháy" },
  confirm_fire_alert: { en: "Confirm Fire Alert", vi: "Xác Nhận Báo Cháy" },
  cancel: { en: "Cancel", vi: "Hủy" },
  delete: { en: "Delete", vi: "Xóa" },
  delete_confirm_desc: { en: "Are you sure you want to delete this notice?", vi: "Bạn có chắc chắn muốn xóa thông báo này không?" },
  activate_alarm: { en: "ACTIVATE ALARM", vi: "KÍCH HOẠT BÁO ĐỘNG" },
  emergency_fire_alert: { en: "EMERGENCY FIRE ALERT", vi: "CẢNH BÁO CHÁY KHẨN CẤP" },
  fire_alert_message: { en: "Resident has triggered an emergency fire alarm. Please evacuate immediately!", vi: "Cư dân đã kích hoạt báo động cháy khẩn cấp. Vui lòng di tản ngay lập tức!" },
  fire_alert_desc: { en: "This will immediately send an emergency evacuation alert to the landlord and all building residents. Only use when there is an active fire.", vi: "Hành động này sẽ gửi cảnh báo di tản khẩn cấp ngay lập tức đến chủ nhà và tất cả cư dân. Chỉ sử dụng khi thực sự có cháy." },
  new_post: { en: "New Post", vi: "Đăng Tin" },
  compose_announcement: { en: "Compose Announcement", vi: "Soạn Thông Báo" },
  alert_level: { en: "Alert Level", vi: "Mức Độ Cảnh Báo" },
  message_content: { en: "Message Content", vi: "Nội Dung Tin Nhắn" },
  type: { en: "Type", vi: "Loại" },
  normal_level: { en: "📢 Normal", vi: "📢 Bình thường" },
  urgent_level: { en: "⚡ Urgent", vi: "⚡ Khẩn cấp" },
  fire_level: { en: "🔥 Fire Alert", vi: "🔥 Cảnh báo cháy" },
  enter_desc: { en: "Enter announcement description...", vi: "Nhập nội dung thông báo..." },
  send: { en: "Send", vi: "Gửi" },
  urgent_notification: { en: "Urgent Notification", vi: "Thông Báo Khẩn" },
  property_notice: { en: "Property Notice", vi: "Thông Báo Tòa Nhà" },
  fire_tap_instruction: { en: "Tap the button below exactly 5 times to confirm and activate the fire alarm.", vi: "Nhấn nút bên dưới đúng 5 lần để xác nhận và kích hoạt báo động cháy." },
  fire_tap_count: { en: "Taps: {count}/5", vi: "Số lần nhấn: {count}/5" },
  fire_tap_warning: { en: "⚠️ ONLY USE IN ACTUAL EMERGENCY FIRE SITUATIONS", vi: "⚠️ CHỈ SỬ DỤNG KHI THỰC SỰ CÓ CHÁY KHẨN CẤP" },
  fire_tap_activate: { en: "CONFIRMING...", vi: "ĐANG KÍCH HOẠT..." },

  // New settings & accessibility translations (Q2, Q3, Q5, Q7)
  properties: { en: "Properties", vi: "Danh Sách Phòng" },
  all_complexes: { en: "All Complexes", vi: "Tất cả khu" },
  add_room: { en: "Add Room", vi: "Thêm phòng" },
  save: { en: "Save", vi: "Lưu" },
  accessibility_settings: { en: "Accessibility & Visuality", vi: "Trực quan & Hỗ trợ" },
  easy_view_mode: { en: "Easy View Mode (Large Text & Easy UI)", vi: "Chế độ Dễ nhìn (Chữ lớn, Trực quan)" },
  language: { en: "Language", vi: "Ngôn ngữ" },
  settings: { en: "Settings", vi: "Cài đặt & Tùy chỉnh" },
  profile: { en: "Personal Profile", vi: "Hồ sơ cá nhân" },
  change_password: { en: "Change Password", vi: "Đổi Mật Khẩu" },
  current_password: { en: "Current Password", vi: "Mật khẩu hiện tại" },
  new_password: { en: "New Password", vi: "Mật khẩu mới" },
  confirm_new_password: { en: "Confirm New Password", vi: "Xác nhận mật khẩu mới" },
  password_changed_success: { en: "Password changed successfully!", vi: "Thay đổi mật khẩu thành công!" },
  cancel_change_password: { en: "Cancel Password Change", vi: "Hủy đổi mật khẩu" },
  proceed_change_password: { en: "Proceed with Password Change", vi: "Tiến hành đổi mật khẩu" },
  please_fill_all_fields: { en: "Please fill in all fields.", vi: "Vui lòng nhập đầy đủ thông tin." },
  post_pending_approval_msg: { en: "Your post has been submitted and is pending review by the landlord.", vi: "Bài viết đã được gửi đi và đang chờ chủ nhà duyệt trước khi hiển thị trên bảng tin." },
  post_title: { en: "Post Title", vi: "Tiêu đề bài viết" },
  enter_title_placeholder: { en: "Enter title...", vi: "Nhập tiêu đề..." },
  attach_media: { en: "Attach Media", vi: "Đính kèm hình ảnh" },
  remove_attachment: { en: "✕ Remove attachment", vi: "✕ Hủy đính kèm" },
  select_mock_image: { en: "📸 Select mock image", vi: "📸 Chọn hình ảnh mẫu" },
  property_manager: { en: "Property Manager", vi: "Quản lý tòa nhà" },
  resident_linked: { en: "Resident", vi: "Cư dân liên kết" },
  past_posts: { en: "PAST POSTS", vi: "LỊCH SỬ TIN ĐÃ ĐĂNG" },
  no_other_posts: { en: "No other posts.", vi: "Không có tin đăng nào khác." },
  unrecorded_electricity: { en: "⚡ UNRECORDED ELECTRICITY", vi: "⚡ CHƯA CHỐT SỐ ĐIỆN" },
  billing_banner_title: { en: "Calculate & Pay this month's invoice", vi: "Tính phí & Thanh toán hóa đơn tháng này" },
  billing_banner_desc: { en: "Snap electricity meter to automatically generate bill via camera", vi: "Chụp ảnh công tơ điện để tự động lập hóa đơn bằng camera" },
  record_now: { en: "Record Now", vi: "Chốt ngay" },
  view_lease: { en: "View Contract", vi: "Xem Hợp Đồng" },
  contact_landlord: { en: "Contact Landlord", vi: "Liên Hệ Chủ Nhà" },
  contact_landlord_title: { en: "Contact Landlord", vi: "Liên Hệ Chủ Nhà" },
  contact_landlord_desc: { en: "Phone: 0901234567\nDo you want to chat on Zalo or make a direct phone call?", vi: "Số điện thoại: 0901234567\nBạn muốn nhắn tin qua Zalo hay gọi điện trực tiếp?" },
  zalo_chat: { en: "Zalo Chat", vi: "Nhắn Zalo" },
  phone_call: { en: "Phone Call", vi: "Gọi Điện" },
  snap_electricity_meter: { en: "Snap Electricity Meter", vi: "Chụp Đồng Hồ Điện" },
  invoice_details: { en: "Invoice Details", vi: "Chi Tiết Hóa Đơn" },
  scan_payment_qr: { en: "Scan QR Payment", vi: "Quét Mã Thanh Toán" },
  ocr_scanning: { en: "Extracting electricity meter index (OCR)...", vi: "Đang trích xuất chỉ số điện (OCR)..." },
  align_meter_desc: { en: "Align the electricity meter inside the frame to scan", vi: "Căn chỉnh chỉ số đồng hồ điện vào khung quét để nhận diện" },
  meter_reading_section: { en: "ELECTRICITY METER & READING", vi: "ĐỒNG HỒ ĐIỆN & CHỈ SỐ" },
  consumption_kwh: { en: "Consumption Index (kWh)", vi: "Chỉ số tiêu dùng (kWh)" },
  enter_meter_kwh: { en: "Enter kWh reading...", vi: "Nhập số kí điện..." },
  monthly_bill_details: { en: "MONTHLY BILL DETAILS", vi: "CHI TIẾT HÓA ĐƠN THÁNG" },
  electricity_bill: { en: "Electricity Fee", vi: "Tiền điện" },
  water_bill: { en: "Water Fee (Fixed)", vi: "Tiền nước (Cố định)" },
  services_bill: { en: "Services & Utilities", vi: "Dịch vụ & Tiện ích" },
  grand_total: { en: "GRAND TOTAL", vi: "TỔNG CỘNG" },
  proceed_to_pay: { en: "Proceed to Payment", vi: "Tiến Hành Thanh Toán" },
  vietqr_transfer: { en: "Transfer via VietQR / MoMo", vi: "Chuyển khoản VietQR / MoMo" },
  vietqr_instruction: { en: "Please scan the QR code below or transfer directly to the bank account listed", vi: "Vui lòng quét mã QR bên dưới hoặc tự chuyển tiền đến thông tin tài khoản bên dưới" },
  payment_amount: { en: "Amount:", vi: "Số tiền:" },
  account_holder: { en: "Account Holder:", vi: "Chủ tài khoản:" },
  account_number: { en: "Account Number:", vi: "Số tài khoản:" },
  transfer_message: { en: "Message:", vi: "Nội dung:" },
  payment_success: { en: "Payment Success", vi: "Thanh toán thành công" },
  payment_success_desc: { en: "Your invoice payment has been recorded successfully!", vi: "Hóa đơn đã được ghi nhận thanh toán thành công!" },
  confirm_transferred: { en: "Confirm Transferred", vi: "Xác Nhận Đã Chuyển Khoản" },
  chat_on_zalo: { en: "💬 Zalo Chat / Contact", vi: "💬 Chat qua Zalo / Liên hệ Zalo" },
  create_lease: { en: "New Lease", vi: "Tạo HĐ" },
  send_reminder: { en: "Remind Fees", vi: "Nhắc Phí" },
  view_reports: { en: "Reports", vi: "Báo Cáo" },
  billing_config: { en: "⚙️ Settings", vi: "⚙️ Cấu hình" },
  notices_approval_requests: { en: "📬 Post Approval Requests", vi: "📬 Yêu Cầu Duyệt Tin Đăng" },
  approve: { en: "Approve", vi: "Duyệt" },
  reject: { en: "Reject", vi: "Từ chối" },
  notification_config_title: { en: "Notification Settings", vi: "Cấu HÌnh Thông Báo" },
  notification_config_success: { en: "Settings Saved", vi: "Cấu hình lưu thành công" },
  notification_config_success_desc: { en: "Billing reminders & contract expiration warning configurations have been saved successfully.", vi: "Hệ thống đã lưu lại các cài đặt thông báo nhắc phí & hết hạn hợp đồng." },
  billing_reminders_config: { en: "BILLING REMINDERS CONFIGURATION", vi: "CẤU HÌNH NHẮC PHÍ ĐỊNH KỲ" },
  billing_day_label: { en: "Billing Reminder Day (Monthly)", vi: "Ngày nhắc phí đầu kỳ (Hằng tháng)" },
  late_billing_days: { en: "Auto-remind late after (days)", vi: "Tự động nhắc trễ sau (ngày)" },
  notification_channels: { en: "Notification Channels:", vi: "Kênh gửi thông báo nhắc phí:" },
  active_rooms_count: { en: "Active rooms:", vi: "Số phòng active:" },
  rooms_unit: { en: "rooms", vi: "phòng" },
  channel_type: { en: "Channel type:", vi: "Kênh gửi tin:" },
  estimated_monthly_channel_cost: { en: "Estimated monthly cost:", vi: "Ước tính phí gửi tin hằng tháng:" },
  lease_expiration_config: { en: "CONTRACT EXPIRATION CONFIGURATION", vi: "CẤU HÌNH HẾT HẠN HỢP ĐỒNG" },
  expiration_warning_days: { en: "Expiration Warning Ahead (Days)", vi: "Số ngày cảnh báo trước hạn" },
  lease_channels: { en: "Contract notification channels:", vi: "Kênh gửi thông báo hợp đồng:" },
  complex_success_title: { en: "Success", vi: "Thành công" },
  complex_success_desc: { en: "New building complex created successfully.", vi: "Đã thêm khu trọ mới thành công." },
  delete_complex_title: { en: "Delete Building Complex", vi: "Xóa Khu Trọ" },
  delete_complex_desc: { en: "Deleting this building complex will also delete all rooms and contracts in it. Do you want to continue?", vi: "Xóa khu trọ này sẽ đồng thời xóa toàn bộ các phòng và hợp đồng nằm trong khu. Bạn có chắc muốn tiếp tục?" },
  manage_complexes_title: { en: "Manage Building Complexes", vi: "Quản lý Khu Trọ" },
  no_complexes_created: { en: "No complexes created yet.", vi: "Chưa có khu trọ nào được tạo." },
  select_complex_label: { en: "Select Complex", vi: "Chọn Khu Trọ" },
  forgot_password: { en: "Forgot Password?", vi: "Quên mật khẩu?" },
  reset_password: { en: "Reset Password", vi: "Khôi phục mật khẩu" },
  send_otp: { en: "Send Verification Code (OTP)", vi: "Gửi mã xác thực (OTP)" },
  enter_otp: { en: "Enter OTP Code", vi: "Nhập mã xác thực" },
  otp_message: { en: "Verification code sent to {phone}. Enter 888888 to verify.", vi: "Mã xác thực đã được gửi đến {phone}. Nhập 888888 để xác nhận." },
  confirm_reset: { en: "Confirm Reset", vi: "Xác nhận đặt lại" },
  reset_success: { en: "Password reset successful! Please log in with your new password.", vi: "Đặt lại mật khẩu thành công! Vui lòng đăng nhập với mật khẩu mới." },
  err_invalid_otp: { en: "Invalid OTP code.", vi: "Mã OTP không hợp lệ." },
  err_phone_not_registered: { en: "This phone number is not registered.", vi: "Số điện thoại này chưa được đăng ký trong hệ thống." },
  err_incorrect_password: { en: "Incorrect current password.", vi: "Mật khẩu hiện tại không chính xác." },
  err_password_mismatch: { en: "New passwords do not match.", vi: "Mật khẩu mới không khớp nhau." },
  err_password_too_short: { en: "Password must be at least 6 characters.", vi: "Mật khẩu phải dài ít nhất 6 ký tự." },
  close: { en: "Close", vi: "Đóng" },
  post_history: { en: "Post History", vi: "Lịch sử tin đã đăng" },
  no_posts: { en: "No post history available.", vi: "Không có tin đăng nào khác." },
  landlord_role: { en: "Landlord (Manager)", vi: "Chủ nhà (Quản lý)" },
  tenant_role: { en: "Linked Resident", vi: "Cư dân liên kết" },
  post_details: { en: "Post Details", vi: "Chi Tiết Tin Đăng" },
  landlord_name: { en: "Landlord", vi: "Chủ nhà" },
  tenant_name: { en: "Nguyễn Thị An", vi: "Nguyễn Thị An" },
  like: { en: "Like", vi: "Thích" },
  comment: { en: "Comment", vi: "Bình luận" },
  comments: { en: "Comments", vi: "Bình luận" },
  send_comment: { en: "Send", vi: "Gửi" },
  write_comment: { en: "Write a comment...", vi: "Viết bình luận..." },
  meter_scan: { en: "Calculate & Pay Rent", vi: "Chốt Số Điện & Thanh Toán" },
  vietqr_payment: { en: "VietQR Payment", vi: "Thanh Toán VietQR" },
  electricity_reading: { en: "Electricity Index consumption (kWh)", vi: "Chỉ số tiêu dùng công tơ điện (kWh)" },
  confirm_payment: { en: "Confirm Transfer Done", vi: "Xác Nhận Đã Chuyển Khoản" },
  ocr_scan_instr: { en: "Align electricity index numbers in frame to capture", vi: "Căn chỉ số điện công tơ vào khung quét" },
  shutter: { en: "Capture Index", vi: "Chụp chỉ số" },
  calculating: { en: "Calculating bill...", vi: "Đang tự động tính hóa đơn..." },
  rent_breakdown: { en: "BILL BREAKDOWN DETAILS", vi: "CHI TIẾT PHÍ THUÊ THÁNG NÀY" },
  electricity: { en: "Electricity cost", vi: "Tiền điện tiêu dùng" },
  water: { en: "Water cost (Flat)", vi: "Tiền nước (Cố định)" },
  service_fee: { en: "Service & Utilities fee", vi: "Dịch vụ & Tiện ích" },
  total_due: { en: "TOTAL RENT PAYMENT", vi: "TỔNG TIỀN PHÒNG THÁNG NÀY" },
  proceed_pay: { en: "Proceed to QR Payment", vi: "Tiến Hành Thanh Toán" },
  config_monetization: { en: "Estimated monthly SaaS notification cost (ZBS Billing):", vi: "Phí dịch vụ gửi tin ước tính hằng tháng (Biểu giá ZBS):" },
  pricing_terms: { en: "* Usage fees will be computed and billed directly to your Zalo Cloud Account (ZCA).", vi: "* Phí sẽ được tính và trừ trực tiếp vào tài khoản Zalo Cloud Account (ZCA) của bạn." },
  manage_complexes: { en: "Manage Complexes", vi: "Quản Lý Khu Trọ" },
  add_complex: { en: "Add Building Complex", vi: "Thêm Khu Trọ Mới" },
  complex_name: { en: "Complex Name (e.g. Oakridge Tower)", vi: "Tên khu trọ (ví dụ: Khu Oakridge)" },
  complex_address: { en: "Complex Address", vi: "Địa chỉ khu trọ" },
  current_complexes: { en: "DANH SÁCH KHU TRỌ HIỆN TẠI", vi: "DANH SÁCH KHU TRỌ HIỆN TẠI" },
  complex: { en: "Complex Group", vi: "Khu trọ" },
  welcome_back: { en: "Welcome Back 👋", vi: "Chào mừng trở lại 👋" },
  dashboard: { en: "Rentify Dashboard", vi: "Bảng điều khiển Rentify" },
  monthly_revenue: { en: "Monthly Revenue", vi: "Doanh thu tháng" },
  lifetime_revenue: { en: "Total Revenue", vi: "Tổng doanh thu" },
  hide_amounts: { en: "Hide amounts", vi: "Ẩn số tiền" },
  show_amounts: { en: "Show amounts", vi: "Hiện số tiền" },
  financials_label: { en: "Pricing", vi: "Giá" },
  unpaid_balance: { en: "Unpaid Balance", vi: "Số tiền chưa thu" },
  occupancy_rate: { en: "Occupancy Rate", vi: "Tỷ lệ lấp đầy" },
  active_leases: { en: "Active Leases", vi: "Hợp đồng hiệu lực" },
  quick_actions: { en: "Quick Actions", vi: "Thao tác nhanh" },
  payment_overview: { en: "Payment Status Overview", vi: "Tổng quan trạng thái" },
  no_payment_data: { en: "No payment data available yet.", vi: "Chưa có dữ liệu thanh toán." },
  paid: { en: "Paid", vi: "Đã thu" },
  pending: { en: "Pending", vi: "Chờ duyệt" },
  overdue: { en: "Overdue", vi: "Quá hạn" },
  recent_payments: { en: "Recent Payments", vi: "Thanh toán gần đây" },
  view_all: { en: "View All", vi: "Xem tất cả" },
  no_recent_payments: { en: "No recent payments logged.", vi: "Chưa có giao dịch gần đây." },
  view_profile: { en: "View Profile", vi: "Xem hồ sơ" },
  revenue_reports: { en: "Revenue & Reports", vi: "Doanh thu & Báo cáo" },
  overview_analysis: { en: "Overview Analysis", vi: "Phân tích tổng quan" },
  collected_income: { en: "Collected Income (Paid):", vi: "Số tiền đã thu (Thành công):" },
  outstanding_invoices: { en: "Outstanding Invoices (Pending):", vi: "Số tiền chưa thu (Chờ):" },
  total_projected: { en: "Total Projected Income:", vi: "Tổng doanh thu dự kiến:" },
  monthly_projections: { en: "Monthly Projections", vi: "Dự kiến doanh thu" },
  average_rent_breakdown: { en: "Average Rent Breakdown", vi: "Cơ cấu giá phòng trung bình" },
  avg_rent_breakdown: { en: "Unpaid Balance", vi: "Chưa thu" },
  projected_revenue: { en: "Total Projected", vi: "Tổng doanh thu dự kiến" },
  tenants: { en: "Tenants", vi: "Người Thuê" },
  add_tenant: { en: "Add Tenant", vi: "Thêm người thuê" },
  contact_info: { en: "Contact Information", vi: "Thông tin liên hệ" },
  name: { en: "Name", vi: "Họ và Tên" },
  email_optional: { en: "Email (Optional)", vi: "Email (Không bắt buộc)" },
  notes: { en: "Notes", vi: "Ghi chú" },
  add_notes_placeholder: { en: "Add any notes...", vi: "Thêm ghi chú..." },
  contact_details: { en: "Contact Details", vi: "Chi tiết liên hệ" },
  leases: { en: "Leases", vi: "Hợp đồng" },
  no_active_leases: { en: "No active leases logged.", vi: "Chưa có hợp đồng hoạt động." },
  no_tenants: { en: "No Tenants", vi: "Chưa có người thuê" },
  add_first_tenant: { en: "Add your first tenant to get started.", vi: "Thêm người thuê đầu tiên để bắt đầu." },
  leasing: { en: "Leasing", vi: "Đang thuê" },
  inactive: { en: "Inactive", vi: "Chưa thuê" },
  logout: { en: "Logout", vi: "Đăng xuất" },

  // Payments tab
  payments_leases: { en: "Payments & Leases", vi: "Thanh toán & Hợp đồng" },
  no_payments: { en: "No Payments", vi: "Chưa có thanh toán" },
  no_payments_for_filter: { en: "No payments found for this filter.", vi: "Không tìm thấy thanh toán nào." },
  filter_all: { en: "All", vi: "Tất cả" },
  filter_paid: { en: "Paid", vi: "Đã thu" },
  filter_pending: { en: "Pending", vi: "Chờ thu" },
  remind_confirm_title: { en: "Send Rent Reminder via Zalo?", vi: "Nhắc tiền phòng qua Zalo?" },
  remind_confirm_msg: { en: "Are you sure you want to remind this tenant about their room payment via Zalo?", vi: "Bạn chắc chắn muốn nhắc lại người này tiền phòng qua Zalo?" },
  remind_confirm_btn: { en: "Send Reminder", vi: "Gửi nhắc" },
  reminder_sent_title: { en: "Reminder Sent", vi: "Đã gửi nhắc" },
  reminder_sent_msg: { en: "Reminder successfully sent via Zalo.", vi: "Đã gửi nhắc qua Zalo thành công." },
  due_label: { en: "Due:", vi: "Hạn:" },
  tenant_label: { en: "Tenant:", vi: "Người thuê:" },
  payment_history: { en: "Payment History", vi: "Lịch sử thanh toán" },
  no_payment_history: { en: "No payment history.", vi: "Chưa có lịch sử thanh toán." },
  record_paid_title: { en: "Confirm Payment", vi: "Xác nhận thanh toán" },
  record_paid_msg: { en: "Record this payment as received?", vi: "Ghi nhận đã thu tiền phòng tháng này?" },
  record_paid_btn: { en: "Record Paid", vi: "Đã thu" },

  // Properties tab
  expiring_soon: { en: "Expiring Soon", vi: "Sắp hết hạn" },
  occupied: { en: "Occupied", vi: "Đang thuê" },
  vacant: { en: "Vacant", vi: "Phòng trống" },
  room_payment_history: { en: "Room Payment History", vi: "Lịch sử thanh toán phòng" },
  no_leases_for_room: { en: "No lease history for this room.", vi: "Phòng này chưa có hợp đồng nào." },
  lease_history: { en: "Lease History", vi: "Lịch sử hợp đồng" },
  monthly_rent_label: { en: "Monthly Rent", vi: "Tiền phòng tháng" },
  security_deposit_label: { en: "Security Deposit", vi: "Tiền cọc" },
  lease_duration_label: { en: "Lease Duration", vi: "Thời hạn hợp đồng" },
  days_remaining: { en: "days remaining", vi: "ngày còn lại" },
  new_lease_title: { en: "New Lease", vi: "Tạo hợp đồng mới" },

  // Community tab
  community_tab: { en: "Community", vi: "Cộng đồng" },
  community_title: { en: "Your Community", vi: "Khu trọ của bạn" },
  community_desc: { en: "Neighbors in your building complex", vi: "Những người cùng khu trọ với bạn" },
  community_empty: { en: "No other tenants found.", vi: "Không tìm thấy người thuê nào khác." },
  room_label: { en: "Room", vi: "Phòng" },
  home: { en: "Home", vi: "Trang chủ" },
  bulletin: { en: "Bulletin", vi: "Thông báo" },

  // Portal / Tenant home
  quick_links: { en: "Quick Links", vi: "Liên kết nhanh" },
  your_payments: { en: "Your Rent Payments", vi: "Lịch sử thanh toán tiền phòng" },
  no_payment_history_tenant: { en: "No payment history logged.", vi: "Chưa có lịch sử thanh toán." },
  active_lease_title: { en: "Active Lease Agreement", vi: "Hợp đồng thuê phòng" },
  rental_address: { en: "Rental Address", vi: "Địa chỉ phòng" },
  lease_duration: { en: "Lease Duration", vi: "Thời hạn hợp đồng" },
  security_deposit: { en: "Security Deposit", vi: "Tiền cọc" },
  monthly_rent: { en: "Monthly Rent", vi: "Tiền phòng/tháng" },
  active_badge: { en: "ACTIVE", vi: "HIỆU LỰC" },

  // Contract / View contract
  rental_agreement: { en: "Rental Agreement", vi: "Hợp đồng thuê nhà" },
  contract_photo_label: { en: "Contract Document", vi: "Ảnh hợp đồng" },
  no_contract_photo: { en: "No contract photo attached.", vi: "Chưa có ảnh hợp đồng đính kèm." },

  // Bank payment flow
  open_bank_app: { en: "Open Bank App", vi: "Mở ứng dụng ngân hàng" },
  bank_redirect_msg: { en: "Opening bank app... Return here after transfer to confirm.", vi: "Đang mở ứng dụng ngân hàng... Quay lại đây sau khi chuyển khoản để xác nhận." },
  payment_confirmed: { en: "Payment Confirmed!", vi: "Xác nhận thanh toán thành công!" },
  payment_confirmed_desc: { en: "Your payment has been recorded. Your home page has been updated.", vi: "Đã ghi nhận thanh toán. Trang chủ của bạn đã được cập nhật." },
  base_rent: { en: "Base Rent", vi: "Tiền phòng" },

  // VI UX feature keys
  add_menu_room: { en: "Add Room", vi: "Thêm phòng" },
  add_menu_complex: { en: "Add Complex", vi: "Thêm khu trọ" },
  add_menu_lease: { en: "Add Lease", vi: "Thêm hợp đồng" },
  room_info: { en: "Room Info", vi: "Thông tin phòng" },
  occupant_section: { en: "Current Occupant", vi: "Người đang ở" },
  price_details: { en: "Price Details", vi: "Chi tiết giá" },
  base_rent_label: { en: "Base rent", vi: "Giá cứng" },
  electricity_rate_label: { en: "Electricity rate", vi: "Giá điện" },
  water_rate_optional: { en: "Water (optional)", vi: "Giá nước" },
  service_fee_optional: { en: "Service fee (optional)", vi: "Giá dịch vụ" },
  parking_fee_optional: { en: "Parking (optional)", vi: "Giá xe" },
  add_custom_fee: { en: "Add other fee", vi: "Thêm giá khác" },
  custom_fee_name: { en: "Fee name", vi: "Tên khoản phí" },
  custom_fee_amount: { en: "Amount (VND)", vi: "Số tiền (VNĐ)" },
  zalo_number: { en: "Zalo number", vi: "Số Zalo" },
  copy_from_phone: { en: "Copy from phone number", vi: "Sao chép từ số điện thoại" },
  tenant_photo: { en: "Tenant photo", vi: "Ảnh người thuê" },
  update_contract_photos: { en: "Update contract photos", vi: "Cập nhật ảnh hợp đồng" },
  contract_last_updated: { en: "Last updated: {date}", vi: "Cập nhật lần cuối: {date}" },
  contract_page_indicator: { en: "Page {current}/{total}", vi: "Trang {current}/{total}" },
  no_occupant: { en: "No current tenant", vi: "Chưa có người thuê" },
  call_action: { en: "Call", vi: "Gọi điện" },
  email_action: { en: "Email", vi: "Gửi email" },
  belongs_to_complex: { en: "Complex", vi: "Thuộc căn/khu" },
  landlord_contact_name: { en: "Name", vi: "Họ tên" },
  dash_empty: { en: "—", vi: "—" },
  landlord_tab_dashboard: { en: "Dashboard", vi: "Tổng quan" },
  landlord_tab_properties: { en: "Properties", vi: "Phòng" },
  landlord_tab_tenants: { en: "Tenants", vi: "Người thuê" },
  landlord_tab_payments: { en: "Payments", vi: "Thanh toán" },
  landlord_tab_notices: { en: "Notices", vi: "Thông báo" },
  save_prices: { en: "Save prices", vi: "Lưu giá" },
  permission_required: { en: "Permission Required", vi: "Cần quyền truy cập" },
  permission_library: { en: "Photo library access is needed.", vi: "Cần quyền truy cập thư viện ảnh." },

  // Task 4: Properties room detail leftovers
  email_label: { en: "Email", vi: "Email" },
  address_label: { en: "Address", vi: "Địa chỉ" },
  property_type_label: { en: "Type", vi: "Loại phòng" },
  bedrooms_label: { en: "Bedrooms", vi: "Phòng ngủ" },
  bathrooms_label: { en: "Bathrooms", vi: "Phòng tắm" },
  remind_day_label: { en: "Remind Day", vi: "Ngày nhắc" },
  remind_day_value: { en: "Day {day} of month", vi: "Ngày {day} hàng tháng" },
  status_label: { en: "Status", vi: "Trạng thái" },
  assign_tenant_action: { en: "👤 Assign Tenant / Create Lease", vi: "👤 Gán người thuê / Tạo hợp đồng" },
  delete_property_title: { en: "Delete Property", vi: "Xóa phòng" },
  delete_property_desc: { en: "Are you sure you want to delete this property? This will also remove any linked leases and payments.", vi: "Bạn có chắc chắn muốn xóa phòng này? Thao tác này sẽ đồng thời xóa các hợp đồng và thanh toán liên quan." },
  delete_property_action: { en: "Delete Property", vi: "Xóa phòng" },
  no_properties_title: { en: "No Properties", vi: "Chưa có phòng nào" },
  no_properties_desc: { en: "Add your first rental property to get started.", vi: "Thêm phòng đầu tiên để bắt đầu." },
  general_information: { en: "General Information", vi: "Thông tin chung" },
  property_name_placeholder: { en: "Property Name (e.g. Oakridge Apt 4B)", vi: "Tên phòng (VD: Phòng 202)" },
  address_placeholder: { en: "Address", vi: "Địa chỉ" },
  financials_size_label: { en: "Pricing", vi: "Giá" },
  monthly_rent_room_label: { en: "Monthly Rent (VND)", vi: "Giá phòng (VNĐ)" },
  electricity_kwh_label: { en: "Electricity (VND/kWh)", vi: "Giá điện (VNĐ/kWh)" },
  water_monthly_label: { en: "Water (Monthly, VND)", vi: "Giá nước (VNĐ/tháng)" },
  service_fee_room_label: { en: "Service Fee (VND)", vi: "Giá dịch vụ (VNĐ)" },
  remind_day_optional_label: { en: "Remind Day (1-28, optional)", vi: "Ngày nhắc phí (1-28, không bắt buộc)" },
  bedrooms_count_label: { en: "Bedrooms: {count}", vi: "Phòng ngủ: {count}" },
  bathrooms_count_label: { en: "Bathrooms: {count}", vi: "Phòng tắm: {count}" },
  type_apartment: { en: "Apartment", vi: "Căn hộ" },
  type_house: { en: "House", vi: "Nhà nguyên căn" },
  type_condo: { en: "Condo", vi: "Chung cư" },
  type_townhouse: { en: "Townhouse", vi: "Nhà phố" },
  unknown_tenant: { en: "Unknown Tenant", vi: "Không rõ" },

  // Task 5: Tenants — photo + Zalo + credentials modal
  delete_tenant_title: { en: "Delete Tenant", vi: "Xóa người thuê" },
  delete_tenant_desc: { en: "Are you sure you want to delete this tenant? This will also remove any linked leases and payments.", vi: "Bạn có chắc chắn muốn xóa người thuê này? Thao tác này sẽ đồng thời xóa các hợp đồng và thanh toán liên quan." },
  choose_photo_action: { en: "Choose Photo", vi: "Chọn ảnh" },
  tenant_created_title: { en: "Tenant Created!", vi: "Đã tạo người thuê!" },
  share_credentials_desc: { en: "Share these credentials with the tenant so they can log in to their account.", vi: "Chia sẻ thông tin đăng nhập này với người thuê để họ có thể đăng nhập vào tài khoản." },
  credential_name_label: { en: "Name:", vi: "Họ tên:" },
  credential_phone_label: { en: "Phone:", vi: "Số điện thoại:" },
  credential_password_label: { en: "Password:", vi: "Mật khẩu:" },
  copy_credentials_action: { en: "📋 Copy Credentials", vi: "📋 Sao chép thông tin" },
  copied_title: { en: "Copied", vi: "Đã sao chép" },
  credentials_copied_desc: { en: "Credentials copied to clipboard!", vi: "Đã sao chép thông tin đăng nhập vào bộ nhớ tạm!" },
  credentials_clipboard_text: { en: "Rentify Login Credentials:\nPhone: {phone}\nPassword: {password}\nPlease change your password in settings after logging in.", vi: "Thông tin đăng nhập Rentify:\nSố điện thoại: {phone}\nMật khẩu: {password}\nVui lòng đổi mật khẩu trong cài đặt sau khi đăng nhập." },

  // Task 7: Hardcode sweep — New Lease modal, photo pickers, reminders, misc
  property_tenant_section: { en: "Property & Tenant", vi: "Phòng & Người thuê" },
  select_property_label: { en: "Select Property:", vi: "Chọn phòng:" },
  select_tenant_label: { en: "Select Tenant:", vi: "Chọn người thuê:" },
  lease_terms_section: { en: "Lease Terms", vi: "Thời hạn thuê" },
  start_date_label: { en: "Start Date", vi: "Ngày bắt đầu" },
  end_date_label: { en: "End Date", vi: "Ngày kết thúc" },
  security_deposit_vnd_label: { en: "Security Deposit (VND)", vi: "Tiền cọc (VNĐ)" },
  attachments_photos_section: { en: "Attachments & Photos", vi: "Đính kèm & Hình ảnh" },
  uploaded_status: { en: "Uploaded", vi: "Đã tải lên" },
  missing_status: { en: "Missing", vi: "Chưa có" },
  upload_action: { en: "Upload", vi: "Tải lên" },
  signed_contract_label: { en: "Signed Contract", vi: "Hợp đồng đã ký" },
  lease_saved_title: { en: "Lease Agreement Saved", vi: "Đã lưu hợp đồng" },
  lease_saved_desc: { en: "Lease has been activated. Invoices were generated.", vi: "Hợp đồng đã được kích hoạt. Hóa đơn đã được tạo." },
  reminders_title: { en: "Reminders", vi: "Nhắc phí" },
  all_invoices_paid: { en: "All invoices are fully paid. No reminders needed!", vi: "Tất cả hóa đơn đã được thanh toán. Không cần nhắc phí!" },
  rent_reminder_push_title: { en: "⚡ Rent Reminder Dispatched", vi: "⚡ Đã gửi nhắc tiền phòng" },
  rent_reminder_push_body: { en: "Sent rent reminders to {count} rooms with outstanding balances.", vi: "Đã gửi nhắc tiền phòng đến {count} phòng còn nợ." },
  reminders_dispatched_title: { en: "Reminders Dispatched", vi: "Đã Gửi Nhắc Phí" },
  reminders_dispatched_desc: { en: "Rent invoice reminders successfully sent to {count} unpaid rooms via Push & Zalo.", vi: "Đã gửi nhắc phí thành công đến {count} phòng chưa thanh toán qua Push & Zalo." },
  performance_insights: { en: "Performance Insights", vi: "Phân Tích Hiệu Suất" },
  phone_label: { en: "Phone", vi: "Số điện thoại" },
  gallery_action: { en: "Gallery", vi: "Thư viện ảnh" },
  select_meter_photo_source_title: { en: "Select Meter Photo Source", vi: "Chọn nguồn ảnh công tơ điện" },
  select_meter_photo_source_desc: { en: "Choose how you want to upload the meter photo:", vi: "Chọn cách bạn muốn tải lên ảnh công tơ điện:" },
  photo_library_action: { en: "Photo Library", vi: "Thư viện ảnh" },
  browse_files_action: { en: "Browse Files", vi: "Duyệt tệp" },
  permission_camera_photos: { en: "Camera access is needed to take photos.", vi: "Cần quyền truy cập máy ảnh để chụp ảnh." },
  permission_library_attach: { en: "Photo library access is needed to attach images.", vi: "Cần quyền truy cập thư viện ảnh để đính kèm hình ảnh." },
  take_photo_action: { en: "Take Photo", vi: "Chụp ảnh" },
  choose_from_library_action: { en: "Choose from Library", vi: "Chọn từ thư viện" },
  select_attachment_source_title: { en: "Select Attachment Source", vi: "Chọn nguồn đính kèm" },
  select_attachment_source_desc: { en: "Choose how you want to upload the document:", vi: "Chọn cách bạn muốn tải lên tài liệu:" },
  switch_active_rental_unit_title: { en: "Switch Active Rental Unit", vi: "Chuyển phòng đang hoạt động" },
  switch_active_room_title: { en: "Switch Active Room", vi: "Chuyển phòng" },
  choose_room_context_desc: { en: "Choose a room context:", vi: "Chọn phòng:" },
  call_failed_title: { en: "Call Failed", vi: "Gọi điện thất bại" },
  call_failed_desc: { en: "Phone calls are not supported on this simulator/device.", vi: "Thiết bị/trình giả lập này không hỗ trợ gọi điện." },
  remind_day_khu_optional_label: { en: "Complex Remind Day (1-28, optional)", vi: "Ngày nhắc phí khu trọ (1-28, không bắt buộc)" },

  // Final-review fixes: validation, room number, OCR helper, performance insights
  room_number: { en: "Room number", vi: "Số phòng" },
  required_title: { en: "Required", vi: "Yêu cầu" },
  khu_fields_required_desc: { en: "Both fields (complex name and address) are required.", vi: "Vui lòng điền đầy đủ cả hai trường tên và địa chỉ." },
  ocr_helper_text: { en: "* Index extracted using camera OCR. You can manually edit it if the recognition is incorrect.", vi: "* Chỉ số được trích xuất bằng camera OCR. Bạn có thể tự chỉnh sửa tay nếu nhận diện sai." },
  insight_occupancy_text: { en: "💡 Your occupancy rate is currently sitting at {rate}%.", vi: "💡 Tỷ lệ lấp đầy hiện tại đang ở mức {rate}%." },
  insight_revenue_text: { en: "Filling vacant rooms could boost monthly revenue by up to {amount}.", vi: "Việc lấp đầy phòng trống có thể giúp tăng doanh thu hàng tháng thêm đến {amount}." },
  invalid_price_title: { en: "Invalid Price", vi: "Giá không hợp lệ" },
  invalid_price_desc: { en: "Please enter a valid rent and electricity rate before saving.", vi: "Vui lòng nhập giá phòng và giá điện hợp lệ trước khi lưu." },
  invalid_fee_title: { en: "Invalid Fee", vi: "Khoản phí không hợp lệ" },
  invalid_fee_desc: { en: "Please enter a valid fee name and amount.", vi: "Vui lòng nhập tên và số tiền hợp lệ cho khoản phí." },

  // Invite code + create lease + room detail + OCR meter
  get_tenant_code: { en: "Get tenant code", vi: "Lấy mã người thuê" },
  tenant_code_label: { en: "Your tenant code", vi: "Mã người thuê của bạn" },
  tenant_code_expires_in: { en: "Expires in {seconds}s", vi: "Hết hạn sau {seconds} giây" },
  tenant_code_expired: { en: "Code expired. Get a new one.", vi: "Mã đã hết hạn. Hãy lấy mã mới." },
  copy_code: { en: "Copy code", vi: "Sao chép mã" },
  code_copied: { en: "Code copied", vi: "Đã sao chép mã" },
  contract_photos_count: { en: "{count} photo(s)", vi: "{count} ảnh" },
  enter_tenant_code: { en: "Tenant code (4 digits)", vi: "Mã người thuê (4 số)" },
  tenant_code_invalid: { en: "The phone number and code do not match.", vi: "Số điện thoại và mã không khớp." },
  tenant_code_hint: {
    en: "The tenant reads this code from their profile.",
    vi: "Người thuê lấy mã này trong trang cá nhân của họ."
  },
  tenant_code_needs_phone: {
    en: "Enter a valid phone number first, then the tenant code.",
    vi: "Nhập số điện thoại hợp lệ trước, sau đó nhập mã người thuê."
  },
  select_complex_first: { en: "Select complex first", vi: "Chọn khu trọ trước" },
  no_vacant_rooms: { en: "No vacant rooms in this complex", vi: "Khu trọ này không còn phòng trống" },
  no_vacant_rooms_hint: {
    en: "All rooms are currently occupied. End a lease or pick another complex.",
    vi: "Tất cả phòng đang có người thuê. Hãy kết thúc hợp đồng hoặc chọn khu khác."
  },
  no_contract_photos_lease: { en: "No contract photos", vi: "Chưa có ảnh hợp đồng" },
  download_action: { en: "Download", vi: "Tải về" },
  download_contract_photo: { en: "Save contract photo", vi: "Lưu ảnh hợp đồng" },
  download_ready_title: { en: "Ready", vi: "Sẵn sàng" },
  download_ready_desc: { en: "Photo is ready. Use the share sheet to save it.", vi: "Ảnh đã sẵn sàng. Dùng bảng chia sẻ để lưu vào máy." },
  download_ready_web_desc: { en: "Opened in a new tab — right-click / long-press to save.", vi: "Đã mở tab mới — chuột phải / giữ để lưu ảnh." },
  download_failed_title: { en: "Download failed", vi: "Tải về thất bại" },
  download_failed_desc: { en: "Could not download this photo. Try again.", vi: "Không tải được ảnh này. Vui lòng thử lại." },
  pinch_to_zoom_hint: { en: "Pinch to zoom · Swipe for next photo", vi: "Chụm để phóng to · Vuốt để xem ảnh khác" },
  select_complex_section: { en: "Select complex", vi: "Chọn khu trọ" },
  select_room_section: { en: "Select room", vi: "Chọn phòng" },
  select_tenant_section: { en: "Select tenant", vi: "Chọn người thuê" },
  search_complex: { en: "Search complexes...", vi: "Tìm khu trọ..." },
  search_room: { en: "Search rooms...", vi: "Tìm phòng..." },
  search_tenant: { en: "Search tenants...", vi: "Tìm người thuê..." },
  create_lease_title: { en: "Create lease", vi: "Tạo hợp đồng" },
  room_tab_info: { en: "Room info", vi: "Thông tin phòng" },
  room_tab_payments: { en: "Payment history", vi: "Lịch sử thanh toán" },
  room_tab_leases: { en: "Lease history", vi: "Lịch sử hợp đồng" },
  meter_prev_reading: { en: "Previous month reading", vi: "Chỉ số điện tháng trước" },
  meter_curr_reading: { en: "This month reading", vi: "Chỉ số điện tháng này" },
  meter_consumption: { en: "kWh used", vi: "Số kí điện sử dụng" },
  meter_manual_confirm: { en: "I confirm the manually entered kWh reading is accurate", vi: "Tôi xác nhận số kí điện đã nhập tay là chính xác" },
  meter_photo_label: { en: "Meter photo", vi: "Ảnh đồng hồ điện" },
  please_confirm_manual_meter: { en: "Please confirm the manual reading before continuing.", vi: "Vui lòng xác nhận số đã nhập tay trước khi tiếp tục." },
};

// Check device language automatically (Q1 requirement)
let deviceLanguage = 'en';
try {
  const locales = Localization.getLocales();
  if (locales && locales.length > 0) {
    const langCode = locales[0].languageCode;
    if (langCode === 'vi') {
      deviceLanguage = 'vi';
    }
  }
} catch (e) {
  console.log('Failed to detect device language, defaulting to en', e);
}

let globalLanguage: Language = deviceLanguage as Language;
const listeners = new Set<(lang: Language) => void>();

export const getLanguage = (): Language => globalLanguage;

export const setLanguage = (lang: Language) => {
  globalLanguage = lang;
  listeners.forEach(listener => listener(lang));
};

export const localF = (key: string, vars: Record<string, string | number>): string => {
  let str = translations[key]?.[globalLanguage] ?? key;
  Object.entries(vars).forEach(([k, v]) => {
    str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
  });
  return str;
};

export const useLanguage = () => {
  const [lang, setLang] = useState<Language>(globalLanguage);

  useEffect(() => {
    listeners.add(setLang);
    return () => {
      listeners.delete(setLang);
    };
  }, []);

  const local = (key: string): string => {
    return translations[key]?.[lang] ?? key;
  };

  const localFWithLang = (key: string, vars: Record<string, string | number>): string => {
    let str = translations[key]?.[lang] ?? key;
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
    });
    return str;
  };

  return { language: lang, setLanguage, local, localF: localFWithLang };
};
